all:
	g++ -std=gnu++11 1901042697.cpp HexAdapter.hpp HexArray1D.cpp HexVector.cpp AbstractHex.h Cell.cpp globalLib.cpp -o 1901042697
	g++ -std=gnu++11 vectorDrive.cpp HexVector.cpp AbstractHex.h Cell.cpp -o vectorDriver
	g++ -std=gnu++11 Array1dDrive.cpp HexArray1D.cpp AbstractHex.h Cell.cpp -o Array1dDriver
	g++ -std=gnu++11 AdaptedVector.cpp HexAdapter.hpp AbstractHex.h Cell.cpp -o AdaptedVectorDriver
	g++ -std=gnu++11 AdaptedDeque.cpp HexAdapter.hpp AbstractHex.h Cell.cpp -o AdaptedDequeDriver


